blank_issues_enabled: false
contact_links:
  - name: Security issue reporting
    url: https://github.com/lumiaurora/subscan/blob/main/SECURITY.md
    about: Please do not report security issues in public issues.
